// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package grpcports

import (
	"github.com/blockysource/authz/cache"
	"github.com/blockysource/authz/deps"
	"github.com/blockysource/authz/ports/grpc/admin"
)

// Injectors from wire.go:

// NewServices creates a new instance of the admin gRPC services.
func NewServices(d *deps.Dependencies, c *cache.Containers) (*Services, func(), error) {
	services, cleanup, err := admingrpc.NewServices(d, c)
	if err != nil {
		return nil, nil, err
	}
	grpcportsServices := &Services{
		admin: services,
	}
	return grpcportsServices, func() {
		cleanup()
	}, nil
}
