// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package postgresadmin

import (
	"log/slog"
)

import (
	_ "embed"
)

// Injectors from wire.go:

// NewKeysStorage creates a new instance of KeysStorage.
func NewKeysStorage(lh slog.Handler) (*KeysStorage, func(), error) {
	logger := newLogger(lh)
	keysStorage := &KeysStorage{
		log: logger,
	}
	return keysStorage, func() {
	}, nil
}

// wire.go:

func newLogger(lh slog.Handler) *slog.Logger {
	return slog.New(lh).With(
		"service", "authz",
		"module", "persistence",
		"component", "admin",
		"driver", "postgres",
	)
}
